# Generated by Django 5.1.15 on 2026-03-15 09:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone number')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('role', models.CharField(choices=[('tutor', 'Tutor'), ('parent', 'Parent/Student'), ('admin', 'Administrator')], default='parent', max_length=10, verbose_name='role')),
                ('auth_provider', models.CharField(choices=[('google', 'Google'), ('phone', 'Phone'), ('email', 'Email')], default='email', max_length=10, verbose_name='authentication provider')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='avatar URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('children_count', models.PositiveIntegerField(default=1, verbose_name='number of children')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('preferred_languages', models.ManyToManyField(blank=True, related_name='interested_parents', to='tutors.language', verbose_name='preferred languages')),
                ('preferred_subjects', models.ManyToManyField(blank=True, related_name='interested_parents', to='tutors.subject', verbose_name='preferred subjects')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
                'db_table': 'parent_profiles',
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='age')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, verbose_name='gender')),
                ('qualifications', models.TextField(blank=True, verbose_name='qualifications')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='years of experience')),
                ('bio', models.TextField(blank=True, help_text='Short description about the tutor', verbose_name='bio')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('teaching_method', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline (In-Person)'), ('both', 'Both')], default='both', max_length=10, verbose_name='teaching method')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price per hour (₹)')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/%Y/%m/', verbose_name='profile photo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('payment_completed', models.BooleanField(default=False, verbose_name='payment completed')),
                ('onboarding_step', models.PositiveIntegerField(default=1, verbose_name='onboarding step')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('languages', models.ManyToManyField(blank=True, related_name='tutor_profiles', to='tutors.language', verbose_name='languages')),
                ('subjects', models.ManyToManyField(blank=True, related_name='tutor_profiles', to='tutors.subject', verbose_name='subjects')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutor Profile',
                'verbose_name_plural': 'Tutor Profiles',
                'db_table': 'tutor_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
