# Generated by Django 5.1.15 on 2026-03-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Format: +919876543210. Used for student connections.', max_length=15, null=True, verbose_name='whatsapp number'),
        ),
    ]
