# Generated by Django 5.1.15 on 2026-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tutorprofile_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='grade_level',
            field=models.CharField(choices=[('all', 'All Levels'), ('elementary', 'Elementary (K-5)'), ('middle', 'Middle School (6-8)'), ('high', 'High School (9-12)'), ('college', 'College')], default='all', max_length=20, verbose_name='grade level'),
        ),
    ]
