# Generated by Django 5.1.15 on 2026-03-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tutorprofile_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price per month (₹)'),
        ),
    ]
